{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "c595e808",
   "metadata": {},
   "outputs": [],
   "source": [
    "from pydantic import BaseModel, ValidationError\n",
    "from datetime import date\n",
    "\n",
    "class Person(BaseModel):\n",
    "    name: str\n",
    "    age: int\n",
    "    birth_date: date"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "ecc1660b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "name='John' age=30 birth_date=datetime.date(1994, 3, 1)\n"
     ]
    }
   ],
   "source": [
    "# Valid data\n",
    "data = {\"name\": \"John\", \"age\": 30, \"birth_date\": \"1994-03-01\"}\n",
    "person = Person(**data)\n",
    "print(person)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "017ff7fa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1 validation error for Person\n",
      "age\n",
      "  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='thirty', input_type=str]\n",
      "    For further information visit https://errors.pydantic.dev/2.11/v/int_parsing\n"
     ]
    }
   ],
   "source": [
    "# Invalid data\n",
    "invalid_data = {\"name\": \"John\", \"age\": \"thirty\", \"birth_date\": \"1994-03-01\"}\n",
    "try:\n",
    "    invalid_person = Person(**invalid_data)\n",
    "except ValidationError as e:\n",
    "    print(e)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "AgenticAI",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
